### PR TITLE
download btn hover refactor

### PR DESCRIPTION
**Pull request by imcotton**
A little refactor, hope this helps.

### CODE REVIEW

**Comment by darscan** [comment]
Thanks!

**Comment by imcotton** [comment]
Glad that I could help, happy shipping on **v2** :thumbsup:

**Comment by darscan** [comment]
Ooops. Just noticed that the links at the very bottom of the page now disappear on hover :/

**Comment by imcotton** [comment]
Oooops, I'm fixing it right way.

**Pull request merged**
